### ISSUE TITLE
"ValueError: not enough values to unpack (expected 5, got 4)" after processing time

### ISSUE THREAD

**Issue by mgc8** [gbabin/rsync-prelude#1]
Hi,

I tried using this very promising tool to optimise the syncing of a couple of media devices. It started running and spent quite a bit of time processing with the processor pegged at 100%, then received the following error:

```
$ sudo ./rsync-prelude -v -e "ssh -c aes128-ctr" -f "'-vaHx'" user@ip:/x/ /volume1/x/
---- find moved/renamed files: ----
run: rsync '-vaHx' -e 'ssh -c aes128-ctr' --list-only user@ip:/x/
user@ip's password:
Traceback (most recent call last):
  File "./rsync-prelude", line 343, in <module>
    main()
  File "./rsync-prelude", line 58, in main
    moves = compute_moves(args)
  File "./rsync-prelude", line 286, in compute_moves
    src_files, dst_files = rsync_list(args, args.SRC), rsync_list(args, DST)
  File "./rsync-prelude", line 122, in rsync_list
    for permissions, size, date, time, path in parsed:
ValueError: not enough values to unpack (expected 5, got 4)
```

If I omit the filter values, it works and I get expected output, but it doesn't do anything as it won't process sub-directories (everything comes up as 'skip'). Is there anything different that I could try to get it to work?

**Comment by gbabin** [comment]
Hello,

Please do not pass any argument to rsync (using `-f`) that modifies its output, like `-v`.
It adds unexpected lines.

**Comment by mgc8** [comment]
Thank you for the clarification, indeed that was the issue. I tested on a small test folder and it worked nicely.

Unfortunately, on the real media storage where I needed this, it ran for about 16h using huge amounts of memory (3GiB+), then it eventually failed with an OOM error... But of course that's a different issue.
